name: Setup
description: Setup Node.js 24 with npm cache and install dependencies

runs:
  using: composite
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: '24'
        registry-url: 'https://npm.pkg.github.com'
        cache: 'npm'

    - run: npm ci
      shell: bash
      env:
        NODE_AUTH_TOKEN: ${{ github.token }}
