// -- model component -------------------------------------------------------------------------------
import IArtboardManagerModel from '../../models/artboard/ArtboardManager';
const _ArtboardManagerModel = new IArtboardManagerModel();
import IArtboardModel from '../../models/artboard/Artboard';
import ITurtleModel from '../../models/artboard/Turtle';
import { useContext, useEffect, useState } from 'react';
import { ArtBoardContext } from '../../context/ArtBoardContext';
import Artboard from './Artboard';
// -- view-model component definition --------------------------------------------------------------

/**
 * ViewModel of the ArtboardManager Framework component.
 */
export default function (): JSX.Element {
  // list of all artboards generated by the user.
  const { artBoardList, setArtBoardList } = useContext(ArtBoardContext);

  // list of IDs of all artboards i.e. artboardIDList.length = artboardList.length .
  const [artboardIDList, setartboardIDList] = useState([0] as number[]);

  // function to add a new Artboard
  const addArtboard = (id: number, x: number, y: number, angle: number) => {
    // check if the artboard with same id already exists.
    const isPresent = artboardIDList.includes(id);
    if (isPresent) {
      return;
    }
    setartboardIDList([...artboardIDList, id]);
    const newTurtle = new ITurtleModel(id, x, y, angle);
    const newArtboard = new IArtboardModel(id, newTurtle);
    _ArtboardManagerModel.addArtboard(newArtboard);
    setArtBoardList([...artBoardList, newArtboard]);
  };

  // manager can initialise several artboards at a time and store them
  // in the artboardList.
  useEffect(() => {
    addArtboard(2, 200, 300, 0); // artboard with id 2.
    addArtboard(4, 300, 300, 0); // artboard with id 4.
    addArtboard(8, 400, 300, 0); // artboard with id 8.
    addArtboard(16, 500, 300, 0); // artboard with id 8.
    addArtboard(32, 600, 300, 0); // artboard with id 8.
    addArtboard(64, 700, 300, 0); // artboard with id 8.
  }, [addArtboard]);

  const moveToTop = (id: number) => {
    for (let i = 0; i < artboardIDList.length; i++) {
      const vid = `art-board-${artboardIDList[i]}`;
      const ele = document.getElementById(vid);
      if (ele === null) continue;
      ele.style.position = 'absolute';
      if (artboardIDList[i] == id) {
        ele.style.zIndex = '10000';
      } else {
        ele.style.zIndex = '5';
      }
    }
  };

  return (
    <>
      <div id="artboard-manager-wrapper">
        <Artboard boards={artBoardList} moveToTop={moveToTop} />
      </div>
    </>
  );
}
