// -- model component -------------------------------------------------------------------------------
import IArtboardManagerModel from '../../models/artboard/ArtboardManager';
const _ArtboardManagerModel = new IArtboardManagerModel();
import IArtboardModel from '../../models/artboard/Artboard';
import { useEffect, useState } from 'react';
import Artboard from './Artboard';
// -- view-model component definition --------------------------------------------------------------

/**
 * ViewModel of the ArtboardManager Framework component.
 */
export default function (): JSX.Element {
  // list of all artboards generated by the user.
  const [artboardList, setartboardList] = useState([] as IArtboardModel[]);

  // list of IDs of all artboards i.e. artboardIDList.length = artboardList.length .
  const [artboardIDList, setartboardIDList] = useState([0] as number[]);

  // function to add a new Artboard
  const addArtboard = (id: number, x: number, y: number, angle: number) => {
    // check if the artboard with same id already exists.
    const isPresent = artboardIDList.includes(id);
    if (isPresent) {
      return;
    }
    setartboardIDList([...artboardIDList, id]);
    const newArtboard = new IArtboardModel(id, x, y, angle);
    _ArtboardManagerModel.addArtboard(newArtboard);
    setartboardList([...artboardList, newArtboard]);
  };

  // manager can initialise several artboards at a time and store them
  // in the artboardList.
  useEffect(() => {
    addArtboard(2, 200, 300, 0); // artboard with id 2.
    addArtboard(4, 220, 300, 0); // artboard with id 4.
    addArtboard(8, 240, 300, 0); // artboard with id 8.
    addArtboard(16, 240, 300, 0); // artboard with id 8.
    addArtboard(32, 240, 300, 0); // artboard with id 8.
    addArtboard(64, 240, 300, 0); // artboard with id 8.
  }, [addArtboard]);

  const moveToTop = (id: number) => {
    for (let i = 0; i < artboardIDList.length; i++) {
      const vid = `art-board-${artboardIDList[i]}`;
      const ele = document.getElementById(vid);
      if (ele === null) continue;
      ele.style.position = 'absolute';
      if (artboardIDList[i] == id) {
        ele.style.zIndex = '10000';
      } else {
        ele.style.zIndex = '5';
      }
    }
  };
  const handleClick2 = () => {
    moveToTop(2);
  };
  const handleClick4 = () => {
    moveToTop(4);
  };
  const handleClick8 = () => {
    moveToTop(8);
  };

  return (
    <>
      <div id="artboard-manager-wrapper">
        <div>
          <button onClick={handleClick2}>Canvas2</button>
          <button onClick={handleClick4}>Canvas4</button>
          <button onClick={handleClick8}>Canvas8</button>
        </div>
        <div>
          {artboardList.map((board) => (
            <Artboard key={board._id} board={board} moveToTop={moveToTop} />
          ))}
        </div>
      </div>
    </>
  );
}
