/**
 * Interface for the message utilities class that is shared by the subcomponent instances of the
 * Monitor and used by the `useMessageEndpoint` hook to establist communication between components
 * and the corresponding Monitor subcomponents.
 *
 * @description This class is meant to be extended by the subcomponent classes and the
 * `useMessageEndpoint` hook.
 */
export interface IMessageUtils {
    /**
     * Saves a `name:method` key-value pair inside the component.
     *
     * @param name - registered name of the method.
     * @param method - registered method callback.
     */
    registerMethod: (name: string, method: CallableFunction) => void;
    /**
     * Removes a `name:method` key-value pair from the component.
     *
     * @param name - registered name of the method.
     * @returns `true` if successful removal else `false`.
     */
    unregisterMethod: (name: string) => boolean;

    /*
     * Since arbitrary arguments can be sent to the following methods, use with caution (arguments
     * might not match method signature).
     */

    /**
     * Calls the method with the given name and passes the arguments.
     *
     * @param name - registered name of the method.
     * @param args - arguments to the method call.
     */
    doMethod: (name: string, ...args: unknown[]) => void;
    /**
     * Calls the method with the given name and passes the arguments, and returns a `Promise` of the
     * returned values.
     *
     * @param name - registered name of the method.
     * @param args - arguments to the method call.
     * @returns `Promise` instance for the returned value if valid method name, else `null`.
     */
    getMethodResult: (name: string, ...args: unknown[]) => Promise<unknown> | null;
    /**
     * Registers a getter and a setter function for the model state object.
     *
     * @description This also adds a force update hook which re-renders the corresponding
     * component when a state is updated.
     *
     * @param stateObject - model instance of the corresponding component.
     */
    registerStateObject: (stateObject: { [key: string]: unknown }) => void;
    /**
     * Returns a model state.
     *
     * @param state - name of the state.
     * @returns value of the state.
     */
    getState: (state: string) => unknown;
    /**
     * Sets a model state.
     *
     * @param state - name of the state.
     * @param value - value to store for the state.
     * */
    setState: (state: string, value: unknown) => void;
    /**
     * Registers the corresponding message endpoint view-model component for the Monitor
     * subcomponent.
     *
     * @description This is meant to be called on the Monitor subcomponent instance only.
     *
     * @param messageEndpoint - message endpoint view-model component instance generated by the
     * `useMessageEndpoint` hook inside the view-model component.
     */
    registerMessageEndpoint: (messageEndpoint: IMessageUtils) => void;
    /**
     * Subscribes a view-model component's model state to a subscription function.
     *
     * @description The subscription function regularly updates the model state whenever the
     * subscription has a new value.
     *
     * @param state - model state name of a view-model component.
     * @param subscription - name of the subscription function.
     */
    subscribe: (state: string, subscription: string) => void;
}

/**
 * Interface for the Monitor component.
 */
export interface IMonitor {
    /** Menu subcomponent instance of Monitor. */
    menu: IMenu;
    /** Palette subcomponent instance of Monitor. */
    palette: IPalette;
    /** Artboard Manager subcomponent instance of Monitor. */
    artboardManager: IManager;
}
