import { useContext, useState } from 'react';
// -- types ----------------------------------------------------------------------------------------

import { IArtboardProps } from '../../@types/artboard';
import { ArtBoardContext } from '../../context/ArtBoardContext';

// -- stylesheet -----------------------------------------------------------------------------------

import './Artboard.scss';
import ArtboardHandler from './ArtboardHandler';
import { ArtboardTurtleSketch } from './ArtboardTurtle';

// -- view component definition --------------------------------------------------------------------

// import { ArtboardSketch, boardSketch } from './ArtboardSketch';
import { TurtleSetup } from './TurtleSetup';

/**
 * View of the Artboard Framework component.
 *
 * @returns root JSX element
 */
export default function (props: IArtboardProps): JSX.Element {
  // list of all artboards generated by the user.
  const { artBoardList } = useContext(ArtBoardContext);
  const [doArc, setDoArc] = useState(false);
  const [doMove, setDoMove] = useState(false);
  const [doRotate, setDoRotate] = useState(false);
  const moveTurtleInArc = () => setDoArc(true);
  const moveTurtleForward = () => setDoMove(true);
  const rotateTurtle = () => setDoRotate(true);
  const [selectedTurtle, setSelectedTurtle] = useState(1);

  const handleDropdownChange = (e: any) => {
    setSelectedTurtle(e.target.value);
  };

  return (
    <>
      <select
        id="dropDown"
        style={{ position: 'absolute', zIndex: 10000000 }}
        onChange={handleDropdownChange}
      >
        {artBoardList.map((artboard, index) => (
          <option key={index} value={artboard._id}>{`Turtle ${artboard._id}`}</option>
        ))}
      </select>
      <button style={{ position: 'absolute', left: 100, zIndex: 1000 }} onClick={moveTurtleInArc}>
        Arc
      </button>
      <button style={{ position: 'absolute', left: 150, zIndex: 1000 }} onClick={moveTurtleForward}>
        Move
      </button>
      <button style={{ position: 'absolute', left: 220, zIndex: 1000 }} onClick={rotateTurtle}>
        Rotate
      </button>

      <div id="artboard-wrapper">
        <h4>Artboard {`(${props.dimensions[0]} × ${props.dimensions[1]})`}</h4>
        {artBoardList.map((board) => (
          <ArtboardHandler
            doArc={doArc}
            setDoArc={setDoArc}
            doMove={doMove}
            setDoMove={setDoMove}
            doRotate={doRotate}
            setDoRotate={setDoRotate}
            key={board._turtle._id}
            index={board._id}
            turtle={board._turtle}
            updateDimensions={props.updateDimensions}
            selectedTurtle={selectedTurtle}
          />
        ))}
      </div>
      <div id="artboard-turtle-wrapper">
        <ArtboardTurtleSketch artBoardList={artBoardList} />
      </div>
    </>
  );
}
