---
# Documentation:https://help.github.com/en/articles/workflow-syntax-for-github-actions

name: Continuous Integration

on:
  pull_request:

jobs:
  type-check:
    name: Verify TypeScript types

    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code base
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: ./.github/actions/setup

      - name: Run Typescript
        run: npm run check

  smoke-test:
    name: Run Smoke Test (build)

    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code base
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: ./.github/actions/setup

      - name: Build for Production
        run: npm run build

  source-test:
    name: Run Tests on Source Code

    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code base
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # - name: Install Cypress dependencies
      #   run: sudo apt update && sudo apt install -y libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb

      - uses: ./.github/actions/setup

      - name: Run Unit Tests
        run: npm run test

      # - name: Cypress run
      #   uses: cypress-io/github-action@v4
      #   with:
      #     build: npm run build:root
      #     start: npm run serve
