---
# Documentation: https://help.github.com/en/articles/workflow-syntax-for-github-actions

name: Linting

on:
  pull_request:
    branches: [develop]

jobs:
  lint:
    name: Lint Code Base

    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code base
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js and install dependencies
        uses: ./.github/actions/setup

      - name: Check formatting (Prettier)
        run: npm run format:check

      - name: Lint files
        run: npm run lint
