---
# Documentation: https://help.github.com/en/articles/workflow-syntax-for-github-actions

name: Linting

on:
  pull_request:
    branches: [develop]

jobs:
  lint:
    name: Lint Code Base

    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code base
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: |
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" >> .npmrc
          npm ci
          npx lerna bootstrap
          rm -rf .npmrc

      - name: Lint files
        run: |
          npm run lint
