---
# Documentation: https://help.github.com/en/articles/workflow-syntax-for-github-actions

name: Super-Linter

on:
  pull_request:
    branches: [develop]

jobs:
  lint:
    name: Lint Code Base

    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code base
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: |
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" >> .npmrc
          npm ci
          rm -rf .npmrc

      - name: Lint new and edited files
        uses: github/super-linter/slim@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BRANCH: develop
          LINTER_RULES_PATH: /
          JAVASCRIPT_ES_CONFIG_FILE: .eslintrc
          TYPESCRIPT_ES_CONFIG_FILE: .eslintrc
          MARKDOWN_CONFIG_FILE: .markdownlint.jsonc
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_CSS: false
          VALIDATE_DOCKERFILE: false
          VALIDATE_DOCKERFILE_HADOLINT: false
          VALIDATE_JAVASCRIPT_STANDARD: false
          VALIDATE_TYPESCRIPT_STANDARD: false
          VALIDATE_JSCPD: false
